//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoboEval.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoursesTaken
    {
        public int CoursesTakenId { get; set; }
        public int TranscriptId { get; set; }
        public int CourseId { get; set; }
        public string Grade { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Transcript Transcript { get; set; }
    }
}
